### ISSUE TITLE
Doesn't work in detached Expo android version

### ISSUE THREAD

**Issue by leo108** [react-community/react-native-image-picker#669]
### Description

I have a detached [expo](https://github.com/expo/expo/) project and I have followed the installation steps. The callback function in `launchImageLibrary` method is not executed after I picked an image from the library, and there is no error message.

### How to repeat issue and example

```
import React from 'react';
import { View, Button } from 'react-native';

var ImagePicker = require('react-native-image-picker');

export default class App extends React.Component {
    selectPhoto() {
        var options = {
          title: 'Select Avatar',
          storageOptions: {
            skipBackup: true,
            path: 'images'
          }
        };
        ImagePicker.launchImageLibrary(options, (response) => {
            console.log(response);
        });
    }
    render() {
        return (
          <View>
            <Button title = "Pick an image" onPress = { this.selectPhoto } />
            </View>
        );
    }
}
```

### Solution

I have no idea.

### Additional Information

* Expo version: 19.0.0
* Platform: Android
* Development Operating System: MacOS

related issue: https://github.com/expo/expo/issues/506

**Comment by Moai-** [comment]
Just spent about five hours today working out post-detachment Expo issues.

Don't know if this will still help you, but in the end, I recreated my entire project with `react-native init` instead of expo, and replaced every dependency I had on it (thankfully, there was only the camera). Expo gets its roots too deep through your code to properly weed out in a timely manner.

**Comment by leo108** [comment]
https://github.com/expo/expo/issues/651#issuecomment-440970379
