### ISSUE TITLE
undefined is not an object(evaluating 'ImagePickerManager.showImagePicker')

### ISSUE THREAD

**Issue by sami718** [react-community/react-native-image-picker#755]
![screen shot 2017-12-15 at 3 24 57 pm](https://user-images.githubusercontent.com/28917467/34036904-b867162a-e1ac-11e7-89b9-d51f09a27fc5.png)

I Imported it as > **var ImagePicker = require('react-native-image-picker');** .
I am using it as follow-
`call() {   
        var options = {
          title: 'Select Avatar',
          customButtons: [
            {name: 'fb', title: 'Choose Photo from Facebook'},
          ],
          storageOptions: {
            skipBackup: true,
            path: 'images'
          }
        };
          ImagePicker.showImagePicker(options, (response) => {
          if (response.didCancel) {
          }
          else if (response.error) {
          }
          else if (response.customButton) {
          }
          else {
            let source = { uri: response.uri };
            // You can also display the image using data:
            // let source = { uri: 'data:image/jpeg;base64,' + response.data };
            this.setState({
              avatarSource: source
            });
          }
        });
      }`
### Additional Information

react-native-image-picker@0.26.7

**Comment by MrKanthaliya** [comment]
Did you solved this issue?

**Comment by brascene** [comment]
Same issue here, so far encountered only on one Android version, 5.1. Any ideas so far?

**Comment by githubmss** [comment]
Getting same error , how to solve it ?

**Comment by budiga** [comment]
I met this problem before.you need to rebuild after linking. Just call react-native run-ios/android after calling react-native-link.Hope it help.

**Comment by arundilipan** [comment]
@budiga I tried that method, but for whatever reason I'm running into the same issue.

**Comment by Hassanjankhan** [comment]
same issue , i am using expo

**Comment by joshterrill** [comment]
Unfortunately, I don't think this repo works with expo... I would love for someone to tell me that I'm wrong. I would love to have a camera solution that doesn't require me to actually code the "Take Photo", "Flip", and "Cancel" buttons myself. From what I can gather, the Camera repo that is in React Native now requires you to do all of that, it really is just a hook into the view of the camera. I was hoping this library would be the answer to that question, so that it would just bring up the phone's camera app (not just the camera view) and let me take a photo or choose a photo from the gallery. But I can't seem to get it to work with the new expo cli. @hasaxena @arundilipan @budiga Let me know if any of you have come across a solution/work around.

**Comment by Jeijie** [comment]
any update? same issue

**Comment by hasaxena** [comment]
@Jeijie I never tried but I believe that this library would not work with Expo since it needs to be linked with Native code. However, I have a small implementation ready for returning Image URI either from Camera or Gallery, but I have used my forked library which has some changes to handle crash on Android Permissions.

`/**
* Import Components from Native/Open NPM packages
*/
import { Alert, } from 'react-native';
import ImagePicker from 'react-native-image-picker';
import OpenSettings from 'react-native-open-settings';

/**
* Constant Strings used as default values for library methods.
*/
const commonTitle = 'Photo App';
const cameraMessage = 'Photo App needs access to your camera and storage so that you can capture and upload paystub.';
const storageMessage = 'Photo App needs access to your storage so that you can choose and upload paystub.';
const ok = 'OK';
const takePhoto = 'Take Photo';
const chooseExisting = 'Choose Existing';
const cancel = 'Cancel';
const settings = 'Settings';

/**
* Default options which will be used, in case no options provided explicitly by calling the method.
* In case of options parameter provided from calling the method, specific values would be replaced.
*/
const DEFAULT_OPTIONS = {
  title: null,
  takePhotoButtonTitle: takePhoto,
  chooseFromLibraryButtonTitle: chooseExisting,
  cancelButtonTitle: cancel,
  allowsEditing: true,
  quality: 1.0,
  storageOptions: {
    skipBackup: true,
    path: 'images',
  },
  permissionDenied: {
    title: commonTitle,
    text: cameraMessage,
    reTryTitle: settings,
    okTitle: ok,
    storageMessage
  },
};

/**
* In case of permission not given in iOS to access Photo Storage or Camera, this method will show message
* to go to Settings and grant the permission.
* +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
* title - Title of the Popup message.
* message - Description of the Popup message.
*
* Note - This method is not used for Android since the library already gives us permission to handle such behavior.
*/
function showPermissionDeniedMessage(title, message) {
  Alert.alert(
    title,
    message,
    [
      { text: settings, onPress: () => OpenSettings.openSettings() },
      { text: ok },
    ],
    { cancelable: false },
  );
}

/**
* This method process response that is returned from Native Camera/Gallery.
*
* +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
* response - response passed from calling the method to process result.
*
* +-+-+-+-+-+-+Response Parameters+-+-+-+-+-+-+
* didCancel - User canceled the operation.
* error - Either permission is not given or system error.
* else - Success, proceed with using the response.
*
* Note - We do not get error object to check which permission rejected/option selected, so we manually check with the message, if that contains
* 'Photo library' or 'Camera' text.
*/
function processResponse(response, options) {
  console.log(response);
  if (response.didCancel) {
    // Do nothing
    return null;
  } else if (response.error) {
    if (response.error.indexOf('Photo library') > -1) {
      showPermissionDeniedMessage(
        options.permissionDenied.title,
        options.permissionDenied.storageMessage,
      );
    } else if (response.error.indexOf('Camera') > -1) {
      showPermissionDeniedMessage(
        options.permissionDenied.title,
        options.permissionDenied.text,
      );
    } else {
      // Do nothing.
    }
    return null;
  }
  // Return the response URI to perform further operation.
  // const source = { uri: response.uri };
  // return source;
  return response;
}

/**
* This is the main method of the whole library, which performs operation either from
* Native Camera or Gallery and gives callback based on response returned from
* operation, either success, didCancel or error.
*
* +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
* options - Options for callee method to Override the values of #DEFAULT_OPTIONS
*
* +-+-+-+-+-+-+Response Parameters+-+-+-+-+-+-+
* resolve - response based on operation (explained above).
*/
export function showImagePicker(options = null) {
  return new Promise((resolve, reject) => {
    ImagePicker.showImagePicker({ ...DEFAULT_OPTIONS, ...options }, (response) => {
      const result = processResponse(response, options);
      if (result !== null) {
        resolve(result);
      } else {
        reject(result);
      }
    });
  });
}

export default { showImagePicker };
`

And to call the exported method use below:
`import { showImagePicker } from './GMImagePicker';

showImagePicker(options)
      .then(source => {
        this.setState({
          imageFilePath: source.uri,
        });
      })
      .catch(error => {
        console.log(error);
      });
`

**Comment by Jeijie** [comment]
@hasaxena

> @Jeijie I never tried but I believe that this library would not work with Expo since it needs to be linked with Native code. However, I have a small implementation ready for returning Image URI either from Camera or Gallery, but I have used my forked library which has some changes to handle crash on Android Permissions.
> 
> ```
> 
> /**
> * Import Components from Native/Open NPM packages
> */
> import { Alert, } from 'react-native';
> import ImagePicker from 'react-native-image-picker';
> import OpenSettings from 'react-native-open-settings';
> 
> /**
> * Constant Strings used as default values for library methods.
> */
> const commonTitle = 'Photo App';
> const cameraMessage = 'Photo App needs access to your camera and storage so that you can capture and upload paystub.';
> const storageMessage = 'Photo App needs access to your storage so that you can choose and upload paystub.';
> const ok = 'OK';
> const takePhoto = 'Take Photo';
> const chooseExisting = 'Choose Existing';
> const cancel = 'Cancel';
> const settings = 'Settings';
> 
> /**
> * Default options which will be used, in case no options provided explicitly by calling the method.
> * In case of options parameter provided from calling the method, specific values would be replaced.
> */
> const DEFAULT_OPTIONS = {
>   title: null,
>   takePhotoButtonTitle: takePhoto,
>   chooseFromLibraryButtonTitle: chooseExisting,
>   cancelButtonTitle: cancel,
>   allowsEditing: true,
>   quality: 1.0,
>   storageOptions: {
>     skipBackup: true,
>     path: 'images',
>   },
>   permissionDenied: {
>     title: commonTitle,
>     text: cameraMessage,
>     reTryTitle: settings,
>     okTitle: ok,
>     storageMessage
>   },
> };
> 
> /**
> * In case of permission not given in iOS to access Photo Storage or Camera, this method will show message
> * to go to Settings and grant the permission.
> * +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
> * title - Title of the Popup message.
> * message - Description of the Popup message.
> *
> * Note - This method is not used for Android since the library already gives us permission to handle such behavior.
> */
> function showPermissionDeniedMessage(title, message) {
>   Alert.alert(
>     title,
>     message,
>     [
>       { text: settings, onPress: () => OpenSettings.openSettings() },
>       { text: ok },
>     ],
>     { cancelable: false },
>   );
> }
> 
> /**
> * This method process response that is returned from Native Camera/Gallery.
> *
> * +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
> * response - response passed from calling the method to process result.
> *
> * +-+-+-+-+-+-+Response Parameters+-+-+-+-+-+-+
> * didCancel - User canceled the operation.
> * error - Either permission is not given or system error.
> * else - Success, proceed with using the response.
> *
> * Note - We do not get error object to check which permission rejected/option selected, so we manually check with the message, if that contains
> * 'Photo library' or 'Camera' text.
> */
> function processResponse(response, options) {
>   console.log(response);
>   if (response.didCancel) {
>     // Do nothing
>     return null;
>   } else if (response.error) {
>     if (response.error.indexOf('Photo library') > -1) {
>       showPermissionDeniedMessage(
>         options.permissionDenied.title,
>         options.permissionDenied.storageMessage,
>       );
>     } else if (response.error.indexOf('Camera') > -1) {
>       showPermissionDeniedMessage(
>         options.permissionDenied.title,
>         options.permissionDenied.text,
>       );
>     } else {
>       // Do nothing.
>     }
>     return null;
>   }
>   // Return the response URI to perform further operation.
>   // const source = { uri: response.uri };
>   // return source;
>   return response;
> }
> 
> /**
> * This is the main method of the whole library, which performs operation either from
> * Native Camera or Gallery and gives callback based on response returned from
> * operation, either success, didCancel or error.
> *
> * +-+-+-+-+-+-+Parameter+-+-+-+-+-+-+
> * options - Options for callee method to Override the values of #DEFAULT_OPTIONS
> *
> * +-+-+-+-+-+-+Response Parameters+-+-+-+-+-+-+
> * resolve - response based on operation (explained above).
> */
> export function showImagePicker(options = null) {
>   return new Promise((resolve, reject) => {
>     ImagePicker.showImagePicker({ ...DEFAULT_OPTIONS, ...options }, (response) => {
>       const result = processResponse(response, options);
>       if (result !== null) {
>         resolve(result);
>       } else {
>         reject(result);
>       }
>     });
>   });
> }
> 
> export default { showImagePicker };
> ```
> And to call the exported method use below:
> 
> ```
> import { showImagePicker } from './GMImagePicker';
> 
> showImagePicker(options)
>       .then(source => {
>         this.setState({
>           imageFilePath: source.uri,
>         });
>       })
>       .catch(error => {
>         console.log(error);
>       });
> ```

**Comment by Jeijie** [comment]
@hasaxena thanks your timely feedback.I fixed this problem by linking manually.

**Comment by Dmitrylolo** [comment]
```
cd ios
pod install
```
